name: Deploy Ecko Backend to GCF

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    # ---- Διάβασε και ΚΑΘΑΡΙΣΕ το Gemini Key ----
    - name: Get and Clean Gemini API Key from Secret Manager
      id: get_gemini_key
      run: |
        RAW_SECRET_VALUE=$(gcloud secrets versions access latest --secret="${{ secrets.GCP_GEMINI_API_KEY_SECRET_NAME }}" --project="${{ secrets.GCP_PROJECT_ID }}" --format='get(payload.data)' | base64 --decode)
        echo "Raw Gemini Key fetched (masked first/last chars): ${RAW_SECRET_VALUE:0:1}*****${RAW_SECRET_VALUE: -1}"
        # Καθάρισε πιθανά artifacts της echo -n '...'
        CLEANED_SECRET_VALUE=$(echo "$RAW_SECRET_VALUE" | sed -e "s/^-n '//" -e "s/'[[:space:]]*$//")
        echo "Cleaned Gemini Key (masked): ${CLEANED_SECRET_VALUE:0:1}*****"
        echo "GEMINI_KEY_VALUE=$CLEANED_SECRET_VALUE" >> $GITHUB_ENV

    # ---- Deploy ----
    - name: Deploy Cloud Function
      env:
          FETCHED_GEMINI_KEY: ${{ env.GEMINI_KEY_VALUE }}
      run: |
        # Χρησιμοποίησε διπλά εισαγωγικά γύρω από το `--set-env-vars` και μονά γύρω από τις τιμές
        gcloud functions deploy ecko-http-function \
          --gen2 \
          --region=us-central1 `# Η περιοχή που λειτουργούσε` \
          --runtime=python311 \
          --memory=512MiB \
          --source=./backend \
          --entry-point=ecko_main \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars="GCP_PROJECT='${{ secrets.GCP_PROJECT_ID }}',GEMINI_API_KEY='${FETCHED_GEMINI_KEY}'" `# Μόνο οι απαραίτητες μεταβλητές` \
          --max-instances=1

    # ---- Βήμα για το URL (παραμένει ίδιο) ----
    - name: Get Function URL
      id: get_url
      run: |
        URL=$(gcloud functions describe ecko-http-function --gen2 --region=us-central1 --format='value(serviceConfig.uri)')
        echo "Function URL: $URL"
        echo "url=$URL" >> $GITHUB_OUTPUT