name: Deploy Ecko Backend to GCF

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Might still be needed by gcloud internally, doesn't hurt to leave it

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Use only Service Account Key for authentication
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}' # Use the Service Account key

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # ---- Deploy ----
    - name: Deploy Cloud Function
      run: |
        # No need to set API keys as env vars when using ADC (which we are not using for the function's runtime)
        # We also removed the code reading the keys, so no need to pass them here.
        gcloud functions deploy ecko-http-function \
          --gen2 \
          --region=us-central1 \
          --runtime=python311 \
          --memory=512MiB \
          --source=./backend \
          --entry-point=ecko_main \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars=GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }} \
          --max-instances=1

    # ---- Get URL ----
    - name: Get Function URL
      id: get_url
      run: |
        URL=$(gcloud functions describe ecko-http-function --gen2 --region=us-central1 --format='value(serviceConfig.uri)')
        echo "Function URL: $URL"
        echo "url=$URL" >> $GITHUB_OUTPUT