name: Deploy Ecko Backend to GCF

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for SA key auth

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}' # Use the Service Account key

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    # ---- Διαβάζει το GitHub PAT Secret (ΧΩΡΙΣ ΚΑΘΑΡΙΣΜΟ) ----
    - name: Get GitHub PAT Secret
      id: get_github_pat
      run: |
        # Διαβάζει το περιεχόμενο του secret - ΧΩΡΙΣ sed
        RAW_PAT=$(gcloud secrets versions access latest --secret="${{ secrets.GCP_GITHUB_PAT_SECRET_NAME }}" --project="${{ secrets.GCP_PROJECT_ID }}" --format='get(payload.data)' | base64 --decode)
        echo "Fetched raw PAT secret (masked)"
        # Κάνε το διαθέσιμο ως environment variable - ΑΠΕΥΘΕΙΑΣ
        echo "::add-mask::$RAW_PAT"
        echo "PAT_VALUE=$RAW_PAT" >> $GITHUB_ENV

    # ---- Deploy ----
    - name: Deploy Cloud Function
      env:
          # Πέρνα την ΑΚΑΘΑΡΙΣΤΗ τιμή του PAT που διαβάστηκε
          RAW_PAT_FROM_WORKFLOW: ${{ env.PAT_VALUE }}
      run: |
        gcloud functions deploy ecko-http-function \
          --gen2 \
          --region=us-central1 `# Παραμένει us-central1` \
          --runtime=python311 \
          --source=./backend \
          --entry-point=ecko_main \
          --trigger-http \
          --allow-unauthenticated \
          --memory=512MiB `# Διατήρηση αυξημένης μνήμης` \
          --set-env-vars=GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }},GITHUB_PAT_VALUE="${RAW_PAT_FROM_WORKFLOW}" `# Πέρνα το ΑΚΑΘΑΡΙΣΤΟ PAT` \
          --max-instances=1

    # ---- Βήμα για το URL (παραμένει ίδιο) ----
    - name: Get Function URL
      id: get_url
      run: |
        URL=$(gcloud functions describe ecko-http-function --gen2 --region=us-central1 --format='value(serviceConfig.uri)')
        echo "Function URL: $URL"