# .github/workflows/deploy-backend.yml
name: Deploy Ecko Backend (Genesis 2.0)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  # Μετονομάστηκε το job ID για σαφήνεια στην εξάρτηση
  deploy_backend_job:
    runs-on: ubuntu-latest
    # --- Minimal Permissions Required (ΟΧΙ variables:write) ---
    permissions:
      contents: 'read'
      id-token: 'write' # Για GCP WIF Auth
      actions: 'write'  # Απαιτείται για upload-artifact
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WIF_POOL_ID }}/providers/${{ secrets.GCP_WIF_PROVIDER_ID }}'
        service_account: '${{ secrets.GCP_SA_EMAIL }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Ecko HTTP Function
      id: deploy
      run: |
        echo "Deploying ecko-http-function..."
        gcloud functions deploy ecko-http-function \
          --gen2 \
          --region=${{ vars.GCP_REGION || 'us-central1' }} \
          --runtime=python311 \
          --source=./backend \
          --entry-point=ecko_main \
          --trigger-http \
          --allow-unauthenticated \
          --memory=${{ vars.GCF_MEMORY || '1GiB' }} \
          --timeout=${{ vars.GCF_TIMEOUT || '540s' }} \
          --max-instances=${{ vars.GCF_MAX_INSTANCES || '2' }} \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --service-account=${{ secrets.GCP_SA_EMAIL }} \
          --set-env-vars=^##^GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}##GCP_GITHUB_PAT_SECRET_NAME=${{ secrets.GCP_GITHUB_PAT_SECRET_NAME }}##GITHUB_REPO_OWNER=${{ github.repository_owner }}##GITHUB_REPO_NAME=${{ github.event.repository.name }}##ECKO_SHARED_SECRET=${{ secrets.ECKO_SHARED_SECRET }}##LOG_LEVEL=INFO##PYTHONUNBUFFERED=1##ALLOWED_ORIGIN=https://${{ github.repository_owner }}.github.io##COMMIT_AUTHOR_EMAIL=${{ secrets.COMMIT_AUTHOR_EMAIL }}

    - name: Get Function URL
      id: get_url
      run: |
        echo "Retrieving function URL..."
        for i in {1..5}; do
          URL=$(gcloud functions describe ecko-http-function --gen2 --project=${{ secrets.GCP_PROJECT_ID }} --region=${{ vars.GCP_REGION || 'us-central1' }} --format='value(serviceConfig.uri)' 2>/dev/null)
          if [ -n "$URL" ]; then
            echo "Function URL retrieved: $URL"
            # Αποθήκευση του URL σε αρχείο
            echo -n "$URL" > backend_url.txt
            echo "URL saved to backend_url.txt"
            exit 0
          fi
          echo "Attempt $i: Function URL not available yet, waiting 10 seconds..."
          sleep 10
        done
        echo "Error: Failed to retrieve function URL after multiple attempts." >&2
        exit 1

    # --- Upload URL Artifact ---
    - name: Upload Backend URL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-url-artifact # Όνομα του artifact
        path: backend_url.txt # Το αρχείο που περιέχει το URL
        retention-days: 1 # Κράτα το artifact μόνο για 1 μέρα

    - name: Display Information
      run: |
        echo "======================================================================="
        echo "Backend deployment finished."
        echo "Backend URL saved in artifact 'backend-url-artifact'."
        echo "Frontend workflow will use this artifact."
        echo "======================================================================="