name: Deploy Ecko Backend to GCF (Vertex AI SDK)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # For GCP authentication

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy ecko-http-function \
          --gen2 \
          --region="europe-west1" \
          --runtime="python311" \
          --source="./backend" \
          --entry-point="ecko_main" \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars="GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" \
          --max-instances=1
      # ΣΗΜΕΙΩΣΗ: Έβαλα εισαγωγικά γύρω από τις τιμές των παραμέτρων
      # και αφαίρεσα το περιττό σχόλιο που μπορεί να μπέρδευε τη συνέχεια γραμμής.

    - name: Get Function URL
      id: get_url
      run: |
        URL=$(gcloud functions describe ecko-http-function --gen2 --region=europe-west1 --format='value(serviceConfig.uri)')
        echo "Function URL: $URL"
        echo "url=$URL" >> $GITHUB_OUTPUT