name: Deploy Ecko Backend to GCF

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml' # Πρόσθεσα και αυτό για να τρέχει αν αλλάξει το workflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    # ---- ΝΕΟ ΒΗΜΑ: Διάβασε το Secret ----
    - name: Get Gemini API Key from Secret Manager
      id: get_gemini_key
      run: |
        SECRET_VALUE=$(gcloud secrets versions access latest --secret="${{ secrets.GCP_GEMINI_API_KEY_SECRET_NAME }}" --project="${{ secrets.GCP_PROJECT_ID }}" --format='get(payload.data)' | base64 --decode)
        echo "Fetched secret value (masked)"
        # Κάνε το διαθέσιμο ως environment variable για το επόμενο βήμα
        echo "GEMINI_KEY_VALUE=$SECRET_VALUE" >> $GITHUB_ENV

    # ---- ΤΡΟΠΟΠΟΙΗΜΕΝΟ ΒΗΜΑ: Deploy ----
    - name: Deploy Cloud Function
      env:
          # Πέρνα την τιμή του κλειδιού που διαβάστηκε στο προηγούμενο βήμα
          FETCHED_GEMINI_KEY: ${{ env.GEMINI_KEY_VALUE }}
      run: |
        gcloud functions deploy ecko-http-function \
          --gen2 \
          --region=europe-west1 \
          --runtime=python311 \
          --source=./backend \
          --entry-point=ecko_main \
          --trigger-http \
          --allow-unauthenticated \
         --set-env-vars=GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }},GEMINI_API_KEY="${FETCHED_GEMINI_KEY}" `# ΔΙΟΡΘΩΣΗ: Προσθήκη εισαγωγικών γύρω από την τιμή` \
          --max-instances=1

    # ---- Βήμα για το URL (παραμένει ίδιο) ----
    - name: Get Function URL
      id: get_url
      run: |
        URL=$(gcloud functions describe ecko-http-function --gen2 --region=europe-west1 --format='value(serviceConfig.uri)')
        echo "Function URL: $URL"
        echo "url=$URL" >> $GITHUB_OUTPUT

    # Προαιρετικό: Ενημέρωση του frontend/script.js με το URL (Απαιτεί PAT)
    # Αυτό είναι μέρος της "αυτο-τροποποίησης" και θα το ενεργοποιήσουμε αργότερα.
    # - name: Update frontend script with function URL
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Προσωρινά χρησιμοποιούμε το GITHUB_TOKEN, θέλει αλλαγή σε PAT αν χρειάζεται push σε protected branch
    #     FUNCTION_URL: ${{ steps.get_url.outputs.url }}
    #   run: |
    #     echo "Updating script.js with URL: $FUNCTION_URL"
    #     sed -i "s|const ECKO_BACKEND_URL = '.*';|const ECKO_BACKEND_URL = '$FUNCTION_URL';|" frontend/script.js
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     git add frontend/script.js
    #     git commit -m "Auto-update backend URL in frontend script [skip ci]" || echo "No changes to commit"
    #     git push # Αυτό θα προκαλέσει νέο build, ίσως χρειάζεται προσοχή ή διαφορετική προσέγγιση (π.χ. commit με [skip ci])